[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["highlighter", "tokio", "debug"] }
log = "0.4.27"
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
tokio = "1.44.2"
